stages:
  - build
  - release

build-job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - 'dotnet build ./Sprint/Sprint.MVC'

release-build_image-job:
  stage: release
  image: docker:19.03.12
  variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE/app:latest
  services:
      - docker:19.03.12-dind
  script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $IMAGE_TAG ./Sprint/Sprint.MVC
      - docker push $IMAGE_TAG
