apiVersion: v1
kind: Secret
metadata:
  name: pv179-deployment-demo-secret
data:
  connectionString: RGF0YSBTb3VyY2U9cHYxNzktbXNzcWwtc3ZjLmRhdWJuZXItbnMuc3ZjLmNsdXN0ZXIubG9jYWw7RGF0YWJhc2U9ZGVtbztVc2VyIElkPXNhO1Bhc3N3b3JkPU15QzBtOWwmeFBAc3N3MHJkOwo=
# Encode to base64: echo "Data Source=(localdb)\ProjectsV13;Initial Catalog=master;Integrated Security=True;" | base64
# Encode to base64: echo "Data Source=pv179-mssql-svc.<YOUR_NAMESPACE>.svc.cluster.local;Database=demo;User Id=sa;Password=MyC0m9l&xP@ssw0rd;" | base64
# pv179-mssql-svc.<YOUR_NAMESPACE>.svc.cluster.local is default cluster DNS. You might supply Cluster IP instead
# SEE: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
